import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '@/lib/api-client';
import { useCompany } from './useCompany';
import { useToast } from './use-toast';

interface AIInsight {
  id: string;
  company_id: string;
  type: string;
  priority: string;
  status: string;
  title: string;
  description: string;
  data: any;
  created_at: string;
  updated_at: string;
}

export function useAIInsights() {
  const { companyId } = useCompany();
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const { data: insights = [], isLoading } = useQuery({
    queryKey: ['ai-insights', companyId],
    queryFn: async () => {
      if (!companyId) return [];
      
      const response = await apiClient.get(`/data/ai_insights?company_id=${companyId}&order=created_at:desc`);
      return response.data as AIInsight[];
    },
    enabled: !!companyId,
  });

  const generateInsights = useMutation({
    mutationFn: async () => {
      if (!companyId) throw new Error('No company ID');
      
      // For now, just return a placeholder - AI insights would be generated by external service
      return { message: 'Insights generation would be implemented with external AI service' };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-insights'] });
      toast({
        title: "Insights gerados",
        description: "Novos insights de IA foram gerados com sucesso!",
      });
    },
  });

  const updateInsightStatus = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: string }) => {
      const response = await apiClient.put(`/data/ai_insights/${id}`, { status });
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-insights'] });
    },
  });

  const dismissInsight = useMutation({
    mutationFn: async (id: string) => {
      const response = await apiClient.put(`/data/ai_insights/${id}`, { status: 'dismissed' });
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-insights'] });
      toast({
        title: "Insight dispensado",
        description: "Insight marcado como dispensado.",
      });
    },
  });

  const implementInsight = useMutation({
    mutationFn: async (id: string) => {
      const response = await apiClient.put(`/data/ai_insights/${id}`, { status: 'implemented' });
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-insights'] });
      toast({
        title: "Insight implementado",
        description: "Insight marcado como implementado!",
      });
    },
  });

  const getInsightsByType = (type: string) => {
    return insights.filter(insight => insight.type === type);
  };

  const getInsightsByPriority = (priority: string) => {
    return insights.filter(insight => insight.priority === priority);
  };

  const getInsightsByStatus = (status: string) => {
    return insights.filter(insight => insight.status === status);
  };

  return {
    insights,
    isLoading,
    generateInsights: generateInsights.mutateAsync,
    updateInsightStatus: updateInsightStatus.mutateAsync,
    dismissInsight: dismissInsight.mutateAsync,
    implementInsight: implementInsight.mutateAsync,
    getInsightsByType,
    getInsightsByPriority,
    getInsightsByStatus,
    isGenerating: generateInsights.isPending,
    isUpdating: updateInsightStatus.isPending,
    isDismissing: dismissInsight.isPending,
    isImplementing: implementInsight.isPending,
  };
}