// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfalcakwtlaqufixgmpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmYWxjYWt3dGxhcXVmaXhnbXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzU1NDMsImV4cCI6MjA2NjUxMTU0M30.pv32GORU45jDgyPCfu75L-E9bKoyeXs8upn4Fuwpblo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);